parameters:
    smartcore.validation.validator.class: Smartbox\CoreBundle\Validation\ValidatorWithExclusion
    smartcore.serialization.subscriber.class: Smartbox\CoreBundle\SerializationHandler\SerializerEventsSubscriber
    smartcore.hydrator.group_version.class: Smartbox\CoreBundle\Hydrator\GroupVersionHydrator

services:
    smartcore.serialization.subscriber:
        class:  %smartcore.serialization.subscriber.class%
        tags:
            - { name: jms_serializer.event_subscriber }

    smartcore.validation.validator:
        class: %smartcore.validation.validator.class%
        decorates: validator
        calls:
            - [ setDecoratedValidator, [ @smartcore.validation.validator.inner ] ]
            - [ setMetadataFactory, [ @jms_serializer.metadata_factory ] ]

    smartcore.hydrator.group_version:
        class: %smartcore.hydrator.group_version.class%
        arguments: [@jms_serializer.metadata_factory]