parameters:
    smartcore.validation.validator.class: Smartbox\CoreBundle\Validation\ValidatorWithExclusion
    smartcore.serialization.subscriber.class: Smartbox\CoreBundle\SerializationHandler\SerializerEventsSubscriber
    smartcore.hydrator.group_version.class: Smartbox\CoreBundle\Hydrator\GroupVersionHydrator
    smartcore.deserialization_casting_checker.class: Smartbox\CoreBundle\Serializer\StrongDeserializationCastingChecker
    smartcore.xml_deserialization_visitor.class: Smartbox\CoreBundle\Serializer\XmlDeserializationVisitor
    smartcore.json_deserialization_visitor.class: Smartbox\CoreBundle\Serializer\JsonDeserializationVisitor

services:
    smartcore.serialization.subscriber:
        class:  %smartcore.serialization.subscriber.class%
        tags:
            - { name: jms_serializer.event_subscriber }

    smartcore.validation.validator:
        class: %smartcore.validation.validator.class%
        decorates: validator
        calls:
            - [ setDecoratedValidator, [ @smartcore.validation.validator.inner ] ]
            - [ setMetadataFactory, [ @jms_serializer.metadata_factory ] ]

    smartcore.hydrator.group_version:
        class: %smartcore.hydrator.group_version.class%
        arguments: [@jms_serializer.metadata_factory]

    smartcore.deserialization_casting_checker:
        class: %smartcore.deserialization_casting_checker.class%

    smartcore.xml_deserialization_visitor:
        class: %smartcore.xml_deserialization_visitor.class%
        parent: jms_serializer.xml_deserialization_visitor
        arguments: [@smartcore.deserialization_casting_checker]
        tags:
            - { name: jms_serializer.deserialization_visitor, format: xml }

    smartcore.json_deserialization_visitor:
        class: %smartcore.json_deserialization_visitor.class%
        parent: jms_serializer.json_deserialization_visitor
        arguments: [@smartcore.deserialization_casting_checker]
        tags:
            - { name: jms_serializer.deserialization_visitor, format: json }
